import React from 'react';
import { IHopprBannerAdProps, IHopprBannerAd } from '../../types';
import { IHopprBannerAdState } from '../interfaces/IHopprBannerAdState';
import { IHopprAdProviderState } from '../interfaces/IHopprAdProviderState';
export declare class HopprBannerAd extends React.Component<IHopprBannerAdProps, IHopprBannerAdState> implements IHopprBannerAd {
    static contextType: React.Context<IHopprAdProviderState>;
    private interactivity;
    private typedContext;
    private matchingAdSlots;
    private instanceUUID;
    private userAgent;
    private webView;
    constructor(props: IHopprBannerAdProps | Readonly<IHopprBannerAdProps>);
    render(): JSX.Element;
    setPressOk(): void;
    setIsSelected(value: boolean): void;
    private getWebView;
    private onShouldStartLoadWithRequest;
    private openExternalLink;
    private getStringifiedSizes;
    private getStringifiedTargetProperties;
    private generateTemplate;
    private isAppleTV;
    private setAdSize;
    private onMessage;
    private triggerInteractivity;
    private logDeeplinkError;
    private logDeeplinkClicked;
    private logGptEvent;
}
